export const data = [
  {
    name: "Afghanistan",
    code: "AF",
    value: "93",
    key: "(+93) Afghanistan",
    flag: "https://restcountries.eu/data/afg.svg",
    currency_value: "AFN",
    currency_label: "Afghan Afghani",
  },
  {
    name: "Albania",
    code: "AL",
    value: "355",
    key: "(+355) Albania",
    flag: "https://restcountries.eu/data/alb.svg",
    currency_value: "ALL",
    currency_label: "Albanian Lek",
  },
  {
    name: "Algeria",
    code: "DZ",
    value: "213",
    key: "(+213) Algeria",
    flag: "https://restcountries.eu/data/dza.svg",
    currency_value: "DZD",
    currency_label: "Algerian Dinar",
  },
  {
    name: "American Samoa",
    code: "AS",
    value: "1684",
    key: "(+1684) American Samoa",
    flag: "https://restcountries.eu/data/asm.svg",
  },
  {
    name: "Andorra",
    code: "AD",
    value: "376",
    key: "(+376) Andorra",
    flag: "https://restcountries.eu/data/and.svg",
    currency_value: "EUR",
    currency_label: "Euro",
  },
  {
    name: "Angola",
    code: "AO",
    value: "244",
    key: "(+244) Angola",
    flag: "https://restcountries.eu/data/ago.svg",
    currency_value: "AOA",
    currency_label: "Angolan Kwanza",
  },
  {
    name: "Anguilla",
    code: "AI",
    value: "1264",
    key: "(+1264) Anguilla",
    flag: "https://restcountries.eu/data/aia.svg",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    value: "1268",
    key: "(+1268) Antigua and Barbuda",
    flag: "https://restcountries.eu/data/atg.svg",
  },
  {
    name: "Argentina",
    code: "AR",
    value: "54",
    key: "(+54) Argentina",
    flag: "https://restcountries.eu/data/arg.svg",
    currency_value: "ARS",
    currency_label: "Argentine Peso",
  },
  {
    name: "Armenia",
    code: "AM",
    value: "374",
    key: "(+374) Armenia",
    flag: "https://restcountries.eu/data/arm.svg",
    currency_value: "AMD",
    currency_label: "Armenian Dram",
  },
  {
    name: "Aruba",
    code: "AW",
    value: "297",
    key: "(+297) Aruba",
    flag: "https://restcountries.eu/data/abw.svg",
  },
  {
    name: "Australia",
    code: "AU",
    value: "61",
    key: "(+61) Australia",
    flag: "https://restcountries.eu/data/aus.svg",
    currency_value: "AUD",
    currency_label: "Australian Dollar",
  },
  {
    name: "Austria",
    code: "AT",
    value: "43",
    key: "(+43) Austria",
    flag: "https://restcountries.eu/data/aut.svg",
    currency_value: "EUR",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    value: "994",
    key: "(+994) Azerbaijan",
    flag: "https://restcountries.eu/data/aze.svg",
    currency_value: "AZN",
    currency_label: "Azerbaijani Manat",
  },
  {
    name: "Bahamas",
    code: "BS",
    value: "1242",
    key: "(+1242) Bahamas",
    flag: "https://restcountries.eu/data/bhs.svg",
  },
  {
    name: "Bahrain",
    code: "BH",
    value: "973",
    key: "(+973) Bahrain",
    flag: "https://restcountries.eu/data/bhr.svg",
    currency_value: "BHD",
    currency_label: "Bahraini Dinar",
  },
  {
    name: "Bangladesh",
    code: "BD",
    value: "880",
    key: "(+880) Bangladesh",
    flag: "https://restcountries.eu/data/bgd.svg",
    currency_value: "BDT",
    currency_label: "Bangladeshi Taka",
  },
  {
    name: "Barbados",
    code: "BB",
    value: "1246",
    key: "(+1246) Barbados",
    flag: "https://restcountries.eu/data/brb.svg",
  },
  {
    name: "Belarus",
    code: "BY",
    value: "375",
    key: "(+375) Belarus",
    flag: "https://restcountries.eu/data/blr.svg",
    currency_value: "BYN",
    currency_label: "Belarusian Ruble",
  },
  {
    name: "Belgium",
    code: "BE",
    value: "32",
    key: "(+32) Belgium",
    flag: "https://restcountries.eu/data/bel.svg",
    currency_value: "EUR",
  },
  {
    name: "Belize",
    code: "BZ",
    value: "501",
    key: "(+501) Belize",
    flag: "https://restcountries.eu/data/blz.svg",
  },
  {
    name: "Benin",
    code: "BJ",
    value: "229",
    key: "(+229) Benin",
    flag: "https://restcountries.eu/data/ben.svg",
    currency_value: "XOF",
    currency_label: "West African CFA franc",
  },
  {
    name: "Bermuda",
    code: "BM",
    value: "1441",
    key: "(+1441) Bermuda",
    flag: "https://restcountries.eu/data/bmu.svg",
  },
  {
    name: "Bhutan",
    code: "BT",
    value: "975",
    key: "(+975) Bhutan",
    flag: "https://restcountries.eu/data/btn.svg",
  },
  {
    name: "(Bolivarian Republic of) Venezuela",
    code: "VE",
    value: "58",
    key: "(+58) (Bolivarian Republic of) Venezuela",
    flag: "https://restcountries.eu/data/ven.svg",
    currency_value: "VES",
    currency_label: "Venezuelan Bolívar",
  },
  {
    name: "Bolivia (Plurinational State of)",
    code: "BO",
    value: "591",
    key: "(+591) Bolivia (Plurinational State of)",
    flag: "https://restcountries.eu/data/bol.svg",
    currency_value: "BOB",
    currency_label: "Bolivian Boliviano",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
    value: "5997",
    key: "(+5997) Bonaire, Sint Eustatius and Saba",
    flag: "https://restcountries.eu/data/bes.svg",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    value: "387",
    key: "(+387) Bosnia and Herzegovina",
    flag: "https://restcountries.eu/data/bih.svg",
    currency_value: "BAM",
    currency_label: "Bosnia-Herzegovina Convertible Mark",
  },
  {
    name: "Botswana",
    code: "BW",
    value: "267",
    key: "(+267) Botswana",
    flag: "https://restcountries.eu/data/bwa.svg",
    currency_value: "BWP",
    currency_label: "Botswana Pula",
  },
  {
    name: "Brazil",
    code: "BR",
    value: "55",
    key: "(+55) Brazil",
    flag: "https://restcountries.eu/data/bra.svg",
    currency_value: "BRL",
    currency_label: "Brazilian Real",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    value: "246",
    key: "(+246) British Indian Ocean Territory",
    flag: "https://restcountries.eu/data/iot.svg",
  },
  {
    name: "Brunei Darussalam",
    code: "BN",
    value: "673",
    key: "(+673) Brunei Darussalam",
    flag: "https://restcountries.eu/data/brn.svg",
    currency_value: "BND",
    currency_label: "Brunei Dollar",
  },
  {
    name: "Bulgaria",
    code: "BG",
    value: "359",
    key: "(+359) Bulgaria",
    flag: "https://restcountries.eu/data/bgr.svg",
    currency_value: "BGN",
    currency_label: "Bulgarian Lev",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    value: "226",
    key: "(+226) Burkina Faso",
    flag: "https://restcountries.eu/data/bfa.svg",
  },
  {
    name: "Burundi",
    code: "BI",
    value: "257",
    key: "(+257) Burundi",
    flag: "https://restcountries.eu/data/bdi.svg",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    value: "238",
    key: "(+238) Cabo Verde",
    flag: "https://restcountries.eu/data/cpv.svg",
    currency_value: "CVE",
    currency_label: "Cape Verdean Escudo",
  },
  {
    name: "Cambodia",
    code: "KH",
    value: "855",
    key: "(+855) Cambodia",
    flag: "https://restcountries.eu/data/khm.svg",
    currency_value: "KHR",
    currency_label: "Cambodian Riel",
  },
  {
    name: "Cameroon",
    code: "CM",
    value: "237",
    key: "(+237) Cameroon",
    flag: "https://restcountries.eu/data/cmr.svg",
    currency_value: "XAF",
    currency_label: "Central African CFA franc",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    value: "1345",
    key: "(+1345) Cayman Islands",
    flag: "https://restcountries.eu/data/cym.svg",
  },
  {
    name: "Central African Republic",
    code: "CF",
    value: "236",
    key: "(+236) Central African Republic",
    flag: "https://restcountries.eu/data/caf.svg",
  },
  {
    name: "Chad",
    code: "TD",
    value: "235",
    key: "(+235) Chad",
    flag: "https://restcountries.eu/data/tcd.svg",
  },
  {
    name: "Chile",
    code: "CL",
    value: "56",
    key: "(+56) Chile",
    flag: "https://restcountries.eu/data/chl.svg",
    currency_value: "CLP",
    currency_label: "Chilean Peso",
  },
  {
    name: "China",
    code: "CN",
    value: "86",
    key: "(+86) China",
    flag: "https://restcountries.eu/data/chn.svg",
    currency_value: "CNY",
    currency_label: "Chinese Yuan",
  },
  {
    name: "Colombia",
    code: "CO",
    value: "57",
    key: "(+57) Colombia",
    flag: "https://restcountries.eu/data/col.svg",
    currency_value: "COP",
    currency_label: "Colombian Peso",
  },
  {
    name: "Comoros",
    code: "KM",
    value: "269",
    key: "(+269) Comoros",
    flag: "https://restcountries.eu/data/com.svg",
  },
  {
    name: "Congo",
    code: "CG",
    value: "242",
    key: "(+242) Congo",
    flag: "https://restcountries.eu/data/cog.svg",
  },
  {
    name: "Congo (Democratic Republic of the)",
    code: "CD",
    value: "243",
    key: "(+243) Congo (Democratic Republic of the)",
    flag: "https://restcountries.eu/data/cod.svg",
  },
  {
    name: "Cook Islands",
    code: "CK",
    value: "682",
    key: "(+682) Cook Islands",
    flag: "https://restcountries.eu/data/cok.svg",
  },
  {
    name: "Costa Rica",
    code: "CR",
    value: "506",
    key: "(+506) Costa Rica",
    flag: "https://restcountries.eu/data/cri.svg",
    currency_value: "CRC",
    currency_label: "Costa Rican Colón",
  },
  {
    name: "Croatia",
    code: "HR",
    value: "385",
    key: "(+385) Croatia",
    flag: "https://restcountries.eu/data/hrv.svg",
    currency_value: "HRK",
    currency_label: "Croatian Kuna",
  },
  {
    name: "Cuba",
    code: "CU",
    value: "53",
    key: "(+53) Cuba",
    flag: "https://restcountries.eu/data/cub.svg",
    currency_value: "CUP",
    currency_label: "Cuban Peso",
  },
  {
    name: "Curaçao",
    code: "CW",
    value: "599",
    key: "(+599) Curaçao",
    flag: "https://restcountries.eu/data/cuw.svg",
  },
  {
    name: "Cyprus",
    code: "CY",
    value: "357",
    key: "(+357) Cyprus",
    flag: "https://restcountries.eu/data/cyp.svg",
    currency_value: "EUR",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    value: "420",
    key: "(+420) Czech Republic",
    flag: "https://restcountries.eu/data/cze.svg",
    currency_value: "CZK",
    currency_label: "Czech Koruna",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    value: "225",
    key: "(+225) Côte d'Ivoire",
    flag: "https://restcountries.eu/data/civ.svg",
    currency_value: "XOF",
    currency_label: "West African CFA franc",
  },
  {
    name: "Denmark",
    code: "DK",
    value: "45",
    key: "(+45) Denmark",
    flag: "https://restcountries.eu/data/dnk.svg",
    currency_value: "DKK",
    currency_label: "Danish Krone",
  },
  {
    name: "Djibouti",
    code: "DJ",
    value: "253",
    key: "(+253) Djibouti",
    flag: "https://restcountries.eu/data/dji.svg",
    currency_value: "DJF",
    currency_label: "Djiboutian Franc",
  },
  {
    name: "Dominica",
    code: "DM",
    value: "1767",
    key: "(+1767) Dominica",
    flag: "https://restcountries.eu/data/dma.svg",
    currency_value: "XCD",
    currency_label: "East Caribbean Dollar",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    value: "1829",
    key: "(+1829) Dominican Republic",
    flag: "https://restcountries.eu/data/dom.svg",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    value: "1849",
    key: "(+1849) Dominican Republic",
    flag: "https://restcountries.eu/data/dom.svg",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    value: "1809",
    key: "(+1809) Dominican Republic",
    flag: "https://restcountries.eu/data/dom.svg",
  },
  {
    name: "Ecuador",
    code: "EC",
    value: "593",
    key: "(+593) Ecuador",
    flag: "https://restcountries.eu/data/ecu.svg",
    currency_value: "USD",
  },
  {
    name: "Egypt",
    code: "EG",
    value: "20",
    key: "(+20) Egypt",
    flag: "https://restcountries.eu/data/egy.svg",
    currency_value: "EGP",
    currency_label: "Egyptian Pound",
  },
  {
    name: "El Salvador",
    code: "SV",
    value: "503",
    key: "(+503) El Salvador",
    flag: "https://restcountries.eu/data/slv.svg",
    currency_value: "USD",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    value: "240",
    key: "(+240) Equatorial Guinea",
    flag: "https://restcountries.eu/data/gnq.svg",
    currency_value: "XAF",
    currency_label: "Central African CFA franc",
  },
  {
    name: "Eritrea",
    code: "ER",
    value: "291",
    key: "(+291) Eritrea",
    flag: "https://restcountries.eu/data/eri.svg",
    currency_value: "ERN",
    currency_label: "Eritrean Nakfa",
  },
  {
    name: "Estonia",
    code: "EE",
    value: "372",
    key: "(+372) Estonia",
    flag: "https://restcountries.eu/data/est.svg",
    currency_value: "EUR",
  },
  {
    name: "Ethiopia",
    code: "ET",
    value: "251",
    key: "(+251) Ethiopia",
    flag: "https://restcountries.eu/data/eth.svg",
    currency_value: "ETB",
    currency_label: "Ethiopian Birr",
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    value: "500",
    key: "(+500) Falkland Islands (Malvinas)",
    flag: "https://restcountries.eu/data/flk.svg",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    value: "298",
    key: "(+298) Faroe Islands",
    flag: "https://restcountries.eu/data/fro.svg",
    currency_value: "DKK",
    currency_label: "Danish Krone",
  },
  {
    name: "Fiji",
    code: "FJ",
    value: "679",
    key: "(+679) Fiji",
    flag: "https://restcountries.eu/data/fji.svg",
    currency_value: "FJD",
    currency_label: "Fijian Dollar",
  },
  {
    name: "Finland",
    code: "FI",
    value: "358",
    key: "(+358) Finland",
    flag: "https://restcountries.eu/data/fin.svg",
    currency_value: "EUR",
  },
  {
    name: "France",
    code: "FR",
    value: "33",
    key: "(+33) France",
    flag: "https://restcountries.eu/data/fra.svg",
    currency_value: "EUR",
  },
  {
    name: "French Guiana",
    code: "GF",
    value: "594",
    key: "(+594) French Guiana",
    flag: "https://restcountries.eu/data/guf.svg",
  },
  {
    name: "French Polynesia",
    code: "PF",
    value: "689",
    key: "(+689) French Polynesia",
    flag: "https://restcountries.eu/data/pyf.svg",
    currency_value: "XPF",
    currency_label: "CFP franc",
  },
  {
    name: "Gabon",
    code: "GA",
    value: "241",
    key: "(+241) Gabon",
    flag: "https://restcountries.eu/data/gab.svg",
    currency_value: "XAF",
    currency_label: "Central African CFA franc",
  },
  {
    name: "Gambia",
    code: "GM",
    value: "220",
    key: "(+220) Gambia",
    flag: "https://restcountries.eu/data/gmb.svg",
    currency_value: "GMD",
    currency_label: "Gambian Dalasi",
  },
  {
    name: "Georgia",
    code: "GE",
    value: "995",
    key: "(+995) Georgia",
    flag: "https://restcountries.eu/data/geo.svg",
    currency_value: "GEL",
    currency_label: "Georgian Lari",
  },
  {
    name: "Germany",
    code: "DE",
    value: "49",
    key: "(+49) Germany",
    flag: "https://restcountries.eu/data/deu.svg",
    currency_value: "EUR",
  },
  {
    name: "Ghana",
    code: "GH",
    value: "233",
    key: "(+233) Ghana",
    flag: "https://restcountries.eu/data/gha.svg",
    currency_value: "GHS",
    currency_label: "Ghanaian Cedi",
  },
  {
    name: "Gibraltar",
    code: "GI",
    value: "350",
    key: "(+350) Gibraltar",
    flag: "https://restcountries.eu/data/gib.svg",
    currency_value: "GIP",
    currency_label: "Gibraltar Pound",
  },
  {
    name: "Greece",
    code: "GR",
    value: "30",
    key: "(+30) Greece",
    flag: "https://restcountries.eu/data/grc.svg",
    currency_value: "EUR",
  },
  {
    name: "Greenland",
    code: "GL",
    value: "299",
    key: "(+299) Greenland",
    flag: "https://restcountries.eu/data/grl.svg",
    currency_value: "DKK",
    currency_label: "Danish Krone",
  },
  {
    name: "Grenada",
    code: "GD",
    value: "1473",
    key: "(+1473) Grenada",
    flag: "https://restcountries.eu/data/grd.svg",
    currency_value: "XCD",
    currency_label: "East Caribbean Dollar",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    value: "590",
    key: "(+590) Guadeloupe",
    flag: "https://restcountries.eu/data/glp.svg",
    currency_value: "EUR",
  },
  {
    name: "Guam",
    code: "GU",
    value: "1671",
    key: "(+1671) Guam",
    flag: "https://restcountries.eu/data/gum.svg",
    currency_value: "USD",
  },
  {
    name: "Guatemala",
    code: "GT",
    value: "502",
    key: "(+502) Guatemala",
    flag: "https://restcountries.eu/data/gtm.svg",
    currency_value: "GTQ",
    currency_label: "Guatemalan Quetzal",
  },
  {
    name: "Guinea",
    code: "GN",
    value: "224",
    key: "(+224) Guinea",
    flag: "https://restcountries.eu/data/gin.svg",
    currency_value: "GNF",
    currency_label: "Guinean Franc",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    value: "245",
    key: "(+245) Guinea-Bissau",
    flag: "https://restcountries.eu/data/gnb.svg",
    currency_value: "XOF",
    currency_label: "West African CFA franc",
  },
  {
    name: "Guyana",
    code: "GY",
    value: "592",
    key: "(+592) Guyana",
    flag: "https://restcountries.eu/data/guy.svg",
    currency_value: "GYD",
    currency_label: "Guyanese Dollar",
  },
  {
    name: "Haiti",
    code: "HT",
    value: "509",
    key: "(+509) Haiti",
    flag: "https://restcountries.eu/data/hti.svg",
    currency_value: "HTG",
    currency_label: "Haitian Gourde",
  },
  {
    name: "Holy See",
    code: "VA",
    value: "379",
    key: "(+379) Holy See",
    flag: "https://restcountries.eu/data/vat.svg",
    currency_value: "EUR",
  },
  {
    name: "Honduras",
    code: "HN",
    value: "504",
    key: "(+504) Honduras",
    flag: "https://restcountries.eu/data/hnd.svg",
    currency_value: "HNL",
    currency_label: "Honduran Lempira",
  },
  {
    name: "Hong Kong",
    code: "HK",
    value: "852",
    key: "(+852) Hong Kong",
    flag: "https://restcountries.eu/data/hkg.svg",
    currency_value: "HKD",
    currency_label: "Hong Kong Dollar",
  },
  {
    name: "Hungary",
    code: "HU",
    value: "36",
    key: "(+36) Hungary",
    flag: "https://restcountries.eu/data/hun.svg",
    currency_value: "HUF",
    currency_label: "Hungarian Forint",
  },
  {
    name: "Iceland",
    code: "IS",
    value: "354",
    key: "(+354) Iceland",
    flag: "https://restcountries.eu/data/isl.svg",
    currency_value: "ISK",
    currency_label: "Icelandic Króna",
  },
  {
    name: "India",
    code: "IN",
    value: "91",
    key: "(+91) India",
    flag: "https://restcountries.eu/data/ind.svg",
    currency_value: "INR",
    currency_label: "Indian Rupee",
  },
  {
    name: "Indonesia",
    code: "ID",
    value: "62",
    key: "(+62) Indonesia",
    flag: "https://restcountries.eu/data/idn.svg",
    currency_value: "IDR",
    currency_label: "Indonesian Rupiah",
  },
  {
    name: "Iran (Islamic Republic of)",
    code: "IR",
    value: "98",
    key: "(+98) Iran (Islamic Republic of)",
    flag: "https://restcountries.eu/data/irn.svg",
    currency_value: "IRR",
    currency_label: "Iranian Rial",
  },
  {
    name: "Iraq",
    code: "IQ",
    value: "964",
    key: "(+964) Iraq",
    flag: "https://restcountries.eu/data/irq.svg",
    currency_value: "IQD",
    currency_label: "Iraqi Dinar",
  },
  {
    name: "Ireland",
    code: "IE",
    value: "353",
    key: "(+353) Ireland",
    flag: "https://restcountries.eu/data/irl.svg",
    currency_value: "EUR",
  },
  {
    name: "Israel",
    code: "IL",
    value: "972",
    key: "(+972) Israel",
    flag: "https://restcountries.eu/data/isr.svg",
    currency_value: "ILS",
    currency_label: "Israeli New Shekel",
  },
  {
    name: "Italy",
    code: "IT",
    value: "39",
    key: "(+39) Italy",
    flag: "https://restcountries.eu/data/ita.svg",
    currency_value: "EUR",
  },
  {
    name: "Jamaica",
    code: "JM",
    value: "1876",
    key: "(+1876) Jamaica",
    flag: "https://restcountries.eu/data/jam.svg",
    currency_value: "JMD",
    currency_label: "Jamaican Dollar",
  },
  {
    name: "Japan",
    code: "JP",
    value: "81",
    key: "(+81) Japan",
    flag: "https://restcountries.eu/data/jpn.svg",
    currency_value: "JPY",
    currency_label: "Japanese Yen",
  },
  {
    name: "Jordan",
    code: "JO",
    value: "962",
    key: "(+962) Jordan",
    flag: "https://restcountries.eu/data/jor.svg",
    currency_value: "JOD",
    currency_label: "Jordanian Dinar",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    value: "76",
    key: "(+76) Kazakhstan",
    flag: "https://restcountries.eu/data/kaz.svg",
    currency_value: "KZT",
    currency_label: "Kazakhstani Tenge",
  },
  {
    name: "Kenya",
    code: "KE",
    value: "254",
    key: "(+254) Kenya",
    flag: "https://restcountries.eu/data/ken.svg",
    currency_value: "KES",
    currency_label: "Kenyan Shilling",
  },
  {
    name: "Kiribati",
    code: "KI",
    value: "686",
    key: "(+686) Kiribati",
    flag: "https://restcountries.eu/data/kir.svg",
    currency_value: "AUD",
  },
  {
    name: "Korea (Democratic People's Republic of)",
    code: "KP",
    value: "850",
    key: "(+850) Korea (Democratic People's Republic of)",
    flag: "https://restcountries.eu/data/prk.svg",
    currency_value: "KPW",
    currency_label: "North Korean Won",
  },
  {
    name: "Kuwait",
    code: "KW",
    value: "965",
    key: "(+965) Kuwait",
    flag: "https://restcountries.eu/data/kwt.svg",
    currency_value: "KWD",
    currency_label: "Kuwaiti Dinar",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    value: "996",
    key: "(+996) Kyrgyzstan",
    flag: "https://restcountries.eu/data/kgz.svg",
    currency_value: "KGS",
    currency_label: "Kyrgyzstani Som",
  },
  {
    name: "Lao People's Democratic Republic",
    code: "LA",
    value: "856",
    key: "(+856) Lao People's Democratic Republic",
    flag: "https://restcountries.eu/data/lao.svg",
    currency_value: "LAK",
    currency_label: "Lao Kip",
  },
  {
    name: "Latvia",
    code: "LV",
    value: "371",
    key: "(+371) Latvia",
    flag: "https://restcountries.eu/data/lva.svg",
    currency_value: "EUR",
  },
  {
    name: "Lebanon",
    code: "LB",
    value: "961",
    key: "(+961) Lebanon",
    flag: "https://restcountries.eu/data/lbn.svg",
    currency_value: "LBP",
    currency_label: "Lebanese Pound",
  },
  {
    name: "Lesotho",
    code: "LS",
    value: "266",
    key: "(+266) Lesotho",
    flag: "https://restcountries.eu/data/lso.svg",
    currency_value: "LSL",
    currency_label: "Lesotho Loti",
  },
  {
    name: "Liberia",
    code: "LR",
    value: "231",
    key: "(+231) Liberia",
    flag: "https://restcountries.eu/data/lbr.svg",
    currency_value: "LRD",
    currency_label: "Liberian Dollar",
  },
  {
    name: "Libya",
    code: "LY",
    value: "218",
    key: "(+218) Libya",
    flag: "https://restcountries.eu/data/lby.svg",
    currency_value: "LYD",
    currency_label: "Libyan Dinar",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    value: "423",
    key: "(+423) Liechtenstein",
    flag: "https://restcountries.eu/data/lie.svg",
    currency_value: "CHF",
    currency_label: "Swiss Franc",
  },
  {
    name: "Lithuania",
    code: "LT",
    value: "370",
    key: "(+370) Lithuania",
    flag: "https://restcountries.eu/data/ltu.svg",
    currency_value: "EUR",
  },
  {
    name: "Luxembourg",
    code: "LU",
    value: "352",
    key: "(+352) Luxembourg",
    flag: "https://restcountries.eu/data/lux.svg",
    currency_value: "EUR",
  },
  {
    name: "Macao",
    code: "MO",
    value: "853",
    key: "(+853) Macao",
    flag: "https://restcountries.eu/data/mac.svg",
    currency_value: "MOP",
    currency_label: "Macanese Pataca",
  },
  {
    name: "Macedonia (the former Yugoslav Republic of)",
    code: "MK",
    value: "389",
    key: "(+389) Macedonia (the former Yugoslav Republic of)",
    flag: "https://restcountries.eu/data/mkd.svg",
    currency_value: "MKD",
    currency_label: "Macedonian Denar",
  },
  {
    name: "Madagascar",
    code: "MG",
    value: "261",
    key: "(+261) Madagascar",
    flag: "https://restcountries.eu/data/mdg.svg",
    currency_value: "MGA",
    currency_label: "Malagasy Ariary",
  },
  {
    name: "Malawi",
    code: "MW",
    value: "265",
    key: "(+265) Malawi",
    flag: "https://restcountries.eu/data/mwi.svg",
    currency_value: "MWK",
    currency_label: "Malawian Kwacha",
  },
  {
    name: "Malaysia",
    code: "MY",
    value: "60",
    key: "(+60) Malaysia",
    flag: "https://restcountries.eu/data/mys.svg",
    currency_value: "MYR",
    currency_label: "Malaysian Ringgit",
  },
  {
    name: "Maldives",
    code: "MV",
    value: "960",
    key: "(+960) Maldives",
    flag: "https://restcountries.eu/data/mdv.svg",
    currency_value: "MVR",
    currency_label: "Maldivian Rufiyaa",
  },
  {
    name: "Mali",
    code: "ML",
    value: "223",
    key: "(+223) Mali",
    flag: "https://restcountries.eu/data/mli.svg",
    currency_value: "XOF",
    currency_label: "West African CFA Franc",
  },
  {
    name: "Malta",
    code: "MT",
    value: "356",
    key: "(+356) Malta",
    flag: "https://restcountries.eu/data/mlt.svg",
    currency_value: "EUR",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    value: "692",
    key: "(+692) Marshall Islands",
    flag: "https://restcountries.eu/data/mhl.svg",
    currency_value: "USD",
    currency_label: "United States Dollar",
  },
  {
    name: "Martinique",
    code: "MQ",
    value: "596",
    key: "(+596) Martinique",
    flag: "https://restcountries.eu/data/mtq.svg",
    currency_value: "EUR",
  },
  {
    name: "Mauritania",
    code: "MR",
    value: "222",
    key: "(+222) Mauritania",
    flag: "https://restcountries.eu/data/mrt.svg",
    currency_value: "MRU",
    currency_label: "Mauritanian Ouguiya",
  },
  {
    name: "Mauritius",
    code: "MU",
    value: "230",
    key: "(+230) Mauritius",
    flag: "https://restcountries.eu/data/mus.svg",
    currency_value: "MUR",
    currency_label: "Mauritian Rupee",
  },
  {
    name: "Mexico",
    code: "MX",
    value: "52",
    key: "(+52) Mexico",
    flag: "https://restcountries.eu/data/mex.svg",
    currency_value: "MXN",
    currency_label: "Mexican Peso",
  },
  {
    name: "Micronesia (Federated States of)",
    code: "FM",
    value: "691",
    key: "(+691) Micronesia (Federated States of)",
    flag: "https://restcountries.eu/data/fsm.svg",
    currency_value: "USD",
  },
  {
    name: "Moldova (Republic of)",
    code: "MD",
    value: "373",
    key: "(+373) Moldova (Republic of)",
    flag: "https://restcountries.eu/data/mda.svg",
    currency_value: "MDL",
    currency_label: "Moldovan Leu",
  },
  {
    name: "Monaco",
    code: "MC",
    value: "377",
    key: "(+377) Monaco",
    flag: "https://restcountries.eu/data/mco.svg",
    currency_value: "EUR",
  },
  {
    name: "Mongolia",
    code: "MN",
    value: "976",
    key: "(+976) Mongolia",
    flag: "https://restcountries.eu/data/mng.svg",
    currency_value: "MNT",
    currency_label: "Mongolian Tugrik",
  },
  {
    name: "Montenegro",
    code: "ME",
    value: "382",
    key: "(+382) Montenegro",
    flag: "https://restcountries.eu/data/mne.svg",
    currency_value: "EUR",
  },
  {
    name: "Montserrat",
    code: "MS",
    value: "1664",
    key: "(+1664) Montserrat",
    flag: "https://restcountries.eu/data/msr.svg",
    currency_value: "XCD",
    currency_label: "East Caribbean Dollar",
  },
  {
    name: "Morocco",
    code: "MA",
    value: "212",
    key: "(+212) Morocco",
    flag: "https://restcountries.eu/data/mar.svg",
    currency_value: "MAD",
    currency_label: "Moroccan Dirham",
  },
  {
    name: "Mozambique",
    code: "MZ",
    value: "258",
    key: "(+258) Mozambique",
    flag: "https://restcountries.eu/data/moz.svg",
    currency_value: "MZN",
    currency_label: "Mozambican Metical",
  },
  {
    name: "Myanmar",
    code: "MM",
    value: "95",
    key: "(+95) Myanmar",
    flag: "https://restcountries.eu/data/mmr.svg",
    currency_value: "MMK",
    currency_label: "Burmese Kyat",
  },
  {
    name: "Namibia",
    code: "NA",
    value: "264",
    key: "(+264) Namibia",
    flag: "https://restcountries.eu/data/nam.svg",
    currency_value: "NAD",
    currency_label: "Namibian Dollar",
  },
  {
    name: "Nauru",
    code: "NR",
    value: "674",
    key: "(+674) Nauru",
    flag: "https://restcountries.eu/data/nru.svg",
    currency_value: "AUD",
  },
  {
    name: "Nepal",
    code: "NP",
    value: "977",
    key: "(+977) Nepal",
    flag: "https://restcountries.eu/data/npl.svg",
    currency_value: "NPR",
    currency_label: "Nepalese Rupee",
  },
  {
    name: "Netherlands",
    code: "NL",
    value: "31",
    key: "(+31) Netherlands",
    flag: "https://restcountries.eu/data/nld.svg",
    currency_value: "EUR",
  },
  {
    name: "New Caledonia",
    code: "NC",
    value: "687",
    key: "(+687) New Caledonia",
    flag: "https://restcountries.eu/data/ncl.svg",
    currency_value: "XPF",
    currency_label: "CFP Franc",
  },
  {
    name: "New Zealand",
    code: "NZ",
    value: "64",
    key: "(+64) New Zealand",
    flag: "https://restcountries.eu/data/nzl.svg",
    currency_value: "NZD",
    currency_label: "New Zealand Dollar",
  },
  {
    name: "Nicaragua",
    code: "NI",
    value: "505",
    key: "(+505) Nicaragua",
    flag: "https://restcountries.eu/data/nic.svg",
    currency_value: "NIO",
    currency_label: "Nicaraguan Córdoba",
  },
  {
    name: "Niger",
    code: "NE",
    value: "227",
    key: "(+227) Niger",
    flag: "https://restcountries.eu/data/ner.svg",
    currency_value: "XOF",
    currency_label: "West African CFA Franc",
  },
  {
    name: "Nigeria",
    code: "NG",
    value: "234",
    key: "(+234) Nigeria",
    flag: "https://restcountries.eu/data/nga.svg",
    currency_value: "NGN",
    currency_label: "Nigerian Naira",
  },
  {
    name: "Niue",
    code: "NU",
    value: "683",
    key: "(+683) Niue",
    flag: "https://restcountries.eu/data/niu.svg",
    currency_value: "NZD",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    value: "672",
    key: "(+672) Norfolk Island/Antarctica",
    flag: "https://restcountries.eu/data/nfk.svg",
    currency_value: "AUD",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    value: "1670",
    key: "(+1670) Northern Mariana Islands",
    flag: "https://restcountries.eu/data/mnp.svg",
    currency_value: "USD",
  },
  {
    name: "Norway",
    code: "NO",
    value: "47",
    key: "(+47) Norway",
    flag: "https://restcountries.eu/data/nor.svg",
    currency_value: "NOK",
    currency_label: "Norwegian Krone",
  },
  {
    name: "Oman",
    code: "OM",
    value: "968",
    key: "(+968) Oman",
    flag: "https://restcountries.eu/data/omn.svg",
    currency_value: "OMR",
    currency_label: "Omani Rial",
  },
  {
    name: "Pakistan",
    code: "PK",
    value: "92",
    key: "(+92) Pakistan",
    flag: "https://restcountries.eu/data/pak.svg",
    currency_value: "PKR",
    currency_label: "Pakistani Rupee",
  },
  {
    name: "Palau",
    code: "PW",
    value: "680",
    key: "(+680) Palau",
    flag: "https://restcountries.eu/data/plw.svg",
    currency_value: "USD",
  },
  {
    name: "Panama",
    code: "PA",
    value: "507",
    key: "(+507) Panama",
    flag: "https://restcountries.eu/data/pan.svg",
    currency_value: "PAB",
    currency_label: "Panamanian Balboa",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    value: "675",
    key: "(+675) Papua New Guinea",
    flag: "https://restcountries.eu/data/png.svg",
    currency_value: "PGK",
    currency_label: "Papua New Guinean Kina",
  },
  {
    name: "Paraguay",
    code: "PY",
    value: "595",
    key: "(+595) Paraguay",
    flag: "https://restcountries.eu/data/pry.svg",
    currency_value: "PYG",
    currency_label: "Paraguayan Guarani",
  },
  {
    name: "Peru",
    code: "PE",
    value: "51",
    key: "(+51) Peru",
    flag: "https://restcountries.eu/data/per.svg",
    currency_value: "PEN",
    currency_label: "Peruvian Sol",
  },
  {
    name: "Philippines",
    code: "PH",
    value: "63",
    key: "(+63) Philippines",
    flag: "https://restcountries.eu/data/phl.svg",
    currency_value: "PHP",
    currency_label: "Philippine Peso",
  },
  {
    name: "Poland",
    code: "PL",
    value: "48",
    key: "(+48) Poland",
    flag: "https://restcountries.eu/data/pol.svg",
    currency_value: "PLN",
    currency_label: "Polish Zloty",
  },
  {
    name: "Portugal",
    code: "PT",
    value: "351",
    key: "(+351) Portugal",
    flag: "https://restcountries.eu/data/prt.svg",
    currency_value: "EUR",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    value: "1787",
    key: "(+1787) Puerto Rico",
    flag: "https://restcountries.eu/data/pri.svg",
    currency_value: "USD",
  },
  {
    name: "Qatar",
    code: "QA",
    value: "974",
    key: "(+974) Qatar",
    flag: "https://restcountries.eu/data/qat.svg",
    currency_value: "QAR",
    currency_label: "Qatari Riyal",
  },
  {
    name: "Republic of Kosovo",
    code: "XK",
    value: "383",
    key: "(+383) Republic of Kosovo",
    flag: "https://restcountries.eu/data/kos.svg",
    currency_value: "EUR",
  },
  {
    name: "(Republic of) Korea",
    code: "KR",
    value: "82",
    key: "(+82) (Republic of) Korea",
    flag: "https://restcountries.eu/data/kor.svg",
    currency_value: "KRW",
    currency_label: "South Korean Won",
  },
  {
    name: "Romania",
    code: "RO",
    value: "40",
    key: "(+40) Romania",
    flag: "https://restcountries.eu/data/rou.svg",
    currency_value: "RON",
    currency_label: "Romanian Leu",
  },
  {
    name: "Russia",
    code: "RU",
    value: "7",
    key: "(+7) Russia",
    flag: "https://restcountries.eu/data/rus.svg",
    currency_value: "RUB",
    currency_label: "Russian Ruble",
  },
  {
    name: "Rwanda",
    code: "RW",
    value: "250",
    key: "(+250) Rwanda",
    flag: "https://restcountries.eu/data/rwa.svg",
    currency_value: "RWF",
    currency_label: "Rwandan Franc",
  },
  {
    name: "Réunion",
    code: "RE",
    value: "262",
    key: "(+262) Réunion",
    flag: "https://restcountries.eu/data/reu.svg",
    currency_value: "EUR",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    value: "290",
    key: "(+290) Saint Helena, Ascension and Tristan da Cunha",
    flag: "https://restcountries.eu/data/shn.svg",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    value: "1869",
    key: "(+1869) Saint Kitts and Nevis",
    flag: "https://restcountries.eu/data/kna.svg",
    currency_value: "XCD",
    currency_label: "East Caribbean Dollar",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    value: "1758",
    key: "(+1758) Saint Lucia",
    flag: "https://restcountries.eu/data/lca.svg",
    currency_value: "XCD",
    currency_label: "East Caribbean Dollar",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    value: "508",
    key: "(+508) Saint Pierre and Miquelon",
    flag: "https://restcountries.eu/data/spm.svg",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    value: "1784",
    key: "(+1784) Saint Vincent and the Grenadines",
    flag: "https://restcountries.eu/data/vct.svg",
    currency_value: "XCD",
    currency_label: "East Caribbean Dollar",
  },
  {
    name: "Samoa",
    code: "WS",
    value: "685",
    key: "(+685) Samoa",
    flag: "https://restcountries.eu/data/wsm.svg",
    currency_value: "WST",
    currency_label: "Samoan Tala",
  },
  {
    name: "San Marino",
    code: "SM",
    value: "378",
    key: "(+378) San Marino",
    flag: "https://restcountries.eu/data/smr.svg",
    currency_value: "EUR",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    value: "239",
    key: "(+239) Sao Tome and Principe",
    flag: "https://restcountries.eu/data/stp.svg",
    currency_value: "STN",
    currency_label: "São Tomé and Príncipe Dobra",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    value: "966",
    key: "(+966) Saudi Arabia",
    flag: "https://restcountries.eu/data/sau.svg",
    currency_value: "SAR",
    currency_label: "Saudi Riyal",
  },
  {
    name: "Senegal",
    code: "SN",
    value: "221",
    key: "(+221) Senegal",
    flag: "https://restcountries.eu/data/sen.svg",
    currency_value: "XOF",
    currency_label: "West African CFA Franc",
  },
  {
    name: "Serbia",
    code: "RS",
    value: "381",
    key: "(+381) Serbia",
    flag: "https://restcountries.eu/data/srb.svg",
    currency_value: "RSD",
    currency_label: "Serbian Dinar",
  },
  {
    name: "Seychelles",
    code: "SC",
    value: "248",
    key: "(+248) Seychelles",
    flag: "https://restcountries.eu/data/syc.svg",
    currency_value: "SCR",
    currency_label: "Seychellois Rupee",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    value: "232",
    key: "(+232) Sierra Leone",
    flag: "https://restcountries.eu/data/sle.svg",
    currency_value: "SLL",
    currency_label: "Sierra Leonean Leone",
  },
  {
    name: "Singapore",
    code: "SG",
    value: "65",
    key: "(+65) Singapore",
    flag: "https://restcountries.eu/data/sgp.svg",
    currency_value: "SGD",
    currency_label: "Singapore Dollar",
  },
  {
    name: "Sint Maarten (Dutch part)",
    code: "SX",
    value: "1721",
    key: "(+1721) Sint Maarten (Dutch part)",
    flag: "https://restcountries.eu/data/sxm.svg",
  },
  {
    name: "Slovakia",
    code: "SK",
    value: "421",
    key: "(+421) Slovakia",
    flag: "https://restcountries.eu/data/svk.svg",
    currency_value: "EUR",
  },
  {
    name: "Slovenia",
    code: "SI",
    value: "386",
    key: "(+386) Slovenia",
    flag: "https://restcountries.eu/data/svn.svg",
    currency_value: "EUR",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    value: "677",
    key: "(+677) Solomon Islands",
    flag: "https://restcountries.eu/data/slb.svg",
    currency_value: "SBD",
    currency_label: "Solomon Islands Dollar",
  },
  {
    name: "Somalia",
    code: "SO",
    value: "252",
    key: "(+252) Somalia",
    flag: "https://restcountries.eu/data/som.svg",
    currency_value: "SOS",
    currency_label: "Somali Shilling",
  },
  {
    name: "South Africa",
    code: "ZA",
    value: "27",
    key: "(+27) South Africa",
    flag: "https://restcountries.eu/data/zaf.svg",
    currency_value: "ZAR",
    currency_label: "South African Rand",
  },
  {
    name: "South Sudan",
    code: "SS",
    value: "211",
    key: "(+211) South Sudan",
    flag: "https://restcountries.eu/data/ssd.svg",
    currency_value: "SSP",
    currency_label: "South Sudanese Pound",
  },
  {
    name: "Spain",
    code: "ES",
    value: "34",
    key: "(+34) Spain",
    flag: "https://restcountries.eu/data/esp.svg",
    currency_value: "EUR",
  },
  {
    name: "Spain",
    code: "ES",
    value: "34",
    key: "(+34) Spain",
    flag: "https://restcountries.eu/data/esp.svg",
    currency_value: "EUR",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    value: "94",
    key: "(+94) Sri Lanka",
    flag: "https://restcountries.eu/data/lka.svg",
    currency_value: "LKR",
    currency_label: "Sri Lankan Rupee",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    value: "94",
    key: "(+94) Sri Lanka",
    flag: "https://restcountries.eu/data/lka.svg",
    currency_value: "LKR",
    currency_label: "Sri Lankan Rupee",
  },
  {
    name: "State of, Palestine",
    code: "PS",
    value: "970",
    key: "(+970) State of, Palestine",
    flag: "https://restcountries.eu/data/pse.svg",
    currency_value: "ILS",
    currency_label: "Israeli New Shekel",
  },
  {
    name: "Sudan",
    code: "SD",
    value: "249",
    key: "(+249) Sudan",
    flag: "https://restcountries.eu/data/sdn.svg",
    currency_value: "SDG",
    currency_label: "Sudanese Pound",
  },
  {
    name: "Sudan",
    code: "SD",
    value: "249",
    key: "(+249) Sudan",
    flag: "https://restcountries.eu/data/sdn.svg",
    currency_value: "SDG",
    currency_label: "Sudanese Pound",
  },
  {
    name: "Suriname",
    code: "SR",
    value: "597",
    key: "(+597) Suriname",
    flag: "https://restcountries.eu/data/sur.svg",
    currency_value: "SRD",
    currency_label: "Surinamese Dollar",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    value: "4779",
    key: "(+4779) Svalbard and Jan Mayen",
    flag: "https://restcountries.eu/data/sjm.svg",
  },
  {
    name: "Swaziland",
    code: "SZ",
    value: "268",
    key: "(+268) Swaziland",
    flag: "https://restcountries.eu/data/swz.svg",
    currency_value: "SZL",
    currency_label: "Swazi Lilangeni",
  },
  {
    name: "Sweden",
    code: "SE",
    value: "46",
    key: "(+46) Sweden",
    flag: "https://restcountries.eu/data/swe.svg",
    currency_value: "SEK",
    currency_label: "Swedish Krona",
  },
  {
    name: "Switzerland",
    code: "CH",
    value: "41",
    key: "(+41) Switzerland",
    flag: "https://restcountries.eu/data/che.svg",
    currency_value: "CHF",
    currency_label: "Swiss Franc",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    value: "963",
    key: "(+963) Syrian Arab Republic",
    flag: "https://restcountries.eu/data/syr.svg",
    currency_value: "SYP",
    currency_label: "Syrian Pound",
  },
  {
    name: "Taiwan",
    code: "TW",
    value: "886",
    key: "(+886) Taiwan",
    flag: "https://restcountries.eu/data/twn.svg",
    currency_value: "TWD",
    currency_label: "New Taiwan Dollar",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    value: "992",
    key: "(+992) Tajikistan",
    flag: "https://restcountries.eu/data/tjk.svg",
    currency_value: "TJS",
    currency_label: "Tajikistani Somoni",
  },
  {
    name: "Thailand",
    code: "TH",
    value: "66",
    key: "(+66) Thailand",
    flag: "https://restcountries.eu/data/tha.svg",
    currency_value: "THB",
    currency_label: "Thai Baht",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    value: "670",
    key: "(+670) Timor-Leste",
    flag: "https://restcountries.eu/data/tls.svg",
    currency_value: "USD",
  },
  {
    name: "Togo",
    code: "TG",
    value: "228",
    key: "(+228) Togo",
    flag: "https://restcountries.eu/data/tgo.svg",
    currency_value: "XOF",
    currency_label: "West African CFA Franc",
  },
  {
    name: "Tokelau",
    code: "TK",
    value: "690",
    key: "(+690) Tokelau",
    flag: "https://restcountries.eu/data/tkl.svg",
  },
  {
    name: "Tonga",
    code: "TO",
    value: "676",
    key: "(+676) Tonga",
    flag: "https://restcountries.eu/data/ton.svg",
    currency_value: "TOP",
    currency_label: "Tongan Pa'anga",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    value: "1868",
    key: "(+1868) Trinidad and Tobago",
    flag: "https://restcountries.eu/data/tto.svg",
    currency_value: "TTD",
    currency_label: "Trinidad and Tobago Dollar",
  },
  {
    name: "Tunisia",
    code: "TN",
    value: "216",
    key: "(+216) Tunisia",
    flag: "https://restcountries.eu/data/tun.svg",
    currency_value: "TND",
    currency_label: "Tunisian Dinar",
  },
  {
    name: "Turkey",
    code: "TR",
    value: "90",
    key: "(+90) Turkey",
    flag: "https://restcountries.eu/data/tur.svg",
    currency_value: "TRY",
    currency_label: "Turkish Lira",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    value: "993",
    key: "(+993) Turkmenistan",
    flag: "https://restcountries.eu/data/tkm.svg",
    currency_value: "TMT",
    currency_label: "Turkmenistan Manat",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    value: "1649",
    key: "(+1649) Turks and Caicos Islands",
    flag: "https://restcountries.eu/data/tca.svg",
  },
  {
    name: "Tuvalu",
    code: "TV",
    value: "688",
    key: "(+688) Tuvalu",
    flag: "https://restcountries.eu/data/tuv.svg",
    currency_value: "AUD",
  },
  {
    name: "Uganda",
    code: "UG",
    value: "256",
    key: "(+256) Uganda",
    flag: "https://restcountries.eu/data/uga.svg",
    currency_value: "UGX",
    currency_label: "Ugandan Shilling",
  },
  {
    name: "Ukraine",
    code: "UA",
    value: "380",
    key: "(+380) Ukraine",
    flag: "https://restcountries.eu/data/ukr.svg",
    currency_value: "UAH",
    currency_label: "Ukrainian Hryvnia",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    value: "971",
    key: "(+971) United Arab Emirates",
    flag: "https://restcountries.eu/data/are.svg",
    currency_value: "AED",
    currency_label: "United Arab Emirates Dirham",
  },
  {
    name: "United Kingdom",
    code: "GB",
    value: "44",
    key: "(+44) United Kingdom",
    flag: "https://restcountries.eu/data/gbr.svg",
    currency_value: "GBP",
    currency_label: "British Pound Sterling",
  },
  {
    name: "United Republic of, Tanzania",
    code: "TZ",
    value: "255",
    key: "(+255) United Republic of, Tanzania",
    flag: "https://restcountries.eu/data/tza.svg",
    currency_value: "TZS",
    currency_label: "Tanzanian Shilling",
  },
  {
    name: "United States of America",
    code: "US",
    value: "1",
    key: "(+1) USA/Canada",
    flag: "https://restcountries.eu/data/usa.svg",
    currency_value: "USD",
    currency_label: "US Dollar",
  },
  {
    name: "Uruguay",
    code: "UY",
    value: "598",
    key: "(+598) Uruguay",
    flag: "https://restcountries.eu/data/ury.svg",
    currency_value: "UYU",
    currency_label: "Uruguayan Peso",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    value: "998",
    key: "(+998) Uzbekistan",
    flag: "https://restcountries.eu/data/uzb.svg",
    currency_value: "UZS",
    currency_label: "Uzbekistan Som",
  },
  {
    name: "Vanuatu",
    code: "VU",
    value: "678",
    key: "(+678) Vanuatu",
    flag: "https://restcountries.eu/data/vut.svg",
    currency_value: "VUV",
    currency_label: "Vanuatu Vatu",
  },
  {
    name: "Vietnam",
    code: "VN",
    value: "84",
    key: "(+84) Vietnam",
    flag: "https://restcountries.eu/data/vnm.svg",
    currency_value: "VND",
    currency_label: "Vietnamese Dong",
  },
  {
    name: "Virgin Islands (British)",
    code: "VG",
    value: "1284",
    key: "(+1284) Virgin Islands (British)",
    flag: "https://restcountries.eu/data/vgb.svg",
  },
  {
    name: "Virgin Islands (U.S.)",
    code: "VI",
    value: "1340",
    key: "(+1340) Virgin Islands (U.S.)",
    flag: "https://restcountries.eu/data/vir.svg",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    value: "681",
    key: "(+681) Wallis and Futuna",
    flag: "https://restcountries.eu/data/wlf.svg",
  },
  {
    name: "Yemen",
    code: "YE",
    value: "967",
    key: "(+967) Yemen",
    flag: "https://restcountries.eu/data/yem.svg",
    currency_value: "YER",
    currency_label: "Yemeni Rial",
  },
  {
    name: "Zambia",
    code: "ZM",
    value: "260",
    key: "(+260) Zambia",
    flag: "https://restcountries.eu/data/zmb.svg",
    currency_value: "ZMW",
    currency_label: "Zambian Kwacha",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    value: "263",
    key: "(+263) Zimbabwe",
    flag: "https://restcountries.eu/data/zwe.svg",
    currency_value: "ZWL",
    currency_label: "Zimbabwean Dollar",
  },
];
